# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x131314ff
bordercolor = 0x919097ff
dropcolor = 0xc5c4db80
splitcolor = 0xdcbecfff
focuscolor = 0xc5c4dbff
maximizescreencolor = 0xc7c5cfff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xdcbecfff
globalcolor = 0x333446ff
overlaycolor = 0x494851ff
jump_label_decorate_fg_color = 0xe5e1e3ff
jump_label_decorate_bg_color = 0x2a2a2bff
jump_label_decorate_focus_fg_color = 0x2e2f41ff
jump_label_decorate_focus_bg_color = 0xc5c4dbff
jump_label_decorate_border_color = 0x919097ff
group_bar_decorate_fg_color = 0xe5e1e3ff
group_bar_decorate_bg_color = 0x2a2a2bff
group_bar_decorate_focus_fg_color = 0x2e2f41ff
group_bar_decorate_focus_bg_color = 0xc5c4dbff
group_bar_decorate_border_color = 0x919097ff
