# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x13142aff
rootcolor = 0x13142aff
bordercolor = 0x606275ff
dropcolor = 0x676de480
splitcolor = 0xc766ccff
focuscolor = 0x676de4ff
maximizescreencolor = 0x935cd6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0xc766ccff
globalcolor = 0x0c128dff
overlaycolor = 0x3b106fff
