local ok, wk = pcall(require, 'which-key')
if not ok then
  return
end

wk.setup({
  delay = 0,
  icons = {
    mappings = vim.g.have_nerd_font,
    keys = vim.g.have_nerd_font and {} or {
      Up = '<Up> ', Down = '<Down> ', Left = '<Left> ', Right = '<Right> ',
      C = '<C-…> ', M = '<M-…> ', D = '<D-…> ', S = '<S-…> ',
      CR = '<CR> ', Esc = '<Esc> ', ScrollWheelDown = '<ScrollWheelDown> ',
      ScrollWheelUp = '<ScrollWheelUp> ', NL = '<NL> ', BS = '<BS> ',
      Space = '<Space> ', Tab = '<Tab> ',
      F1 = '<F1>', F2 = '<F2>', F3 = '<F3>', F4 = '<F4>', F5 = '<F5>',
      F6 = '<F6>', F7 = '<F7>', F8 = '<F8>', F9 = '<F9>', F10 = '<F10>',
      F11 = '<F11>', F12 = '<F12>',
    },
  },
  spec = {
    { '<leader>s', group = '[S]earch' },
    { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
  },
})

wk.add({
  { '<leader>b', group = 'buffer / breakpoint' },
  { '[b', desc = 'Previous buffer' },
  { ']b', desc = 'Next buffer' },
  { '<leader>bb', desc = 'Alternate buffer' },
  { '<leader>c', group = 'code / copy' },
  { '<leader>d', group = 'debug' },
  { '<leader>f', group = 'find / files' },
  { '<leader>g', group = 'git' },
  { '<leader>q', group = 'quickfix' },
  { '<leader>r', group = 'review / diff' },
  { '<leader>s', group = 'search / symbols' },
  { '<leader>t', group = 'terminal / toggle' },
  { '<leader>tt', desc = 'Toggle terminal' },
  { '<leader>tf', desc = 'Floating terminal' },
  { '<leader>th', desc = 'Horizontal terminal' },
  { '<leader>tv', desc = 'Vertical terminal' },
  { '<leader>tm', desc = 'Cycle terminal mode' },
  { '<leader>O', group = 'overseer / tasks' },
  { '<leader>S', group = 'sessions' },
  { '<leader>T', group = 'tests' },
  { '<leader>x', group = 'diagnostics / trouble' },
  { '<leader>w', group = 'window / write' },
  { '<leader>wv', desc = 'Vertical split' },
  { '<leader>ws', desc = 'Horizontal split' },
  { '<leader>wq', desc = 'Close window' },
  { '<leader>w=', desc = 'Equalize windows' },
  { '<leader><leader>', desc = 'Find files' },
  { '<leader>/', desc = 'Live grep' },
  { '<leader>,', desc = 'Buffers' },
  { '<leader>.', desc = 'Recent files' },
  { '<leader>;', desc = 'Resume search' },
  { '<leader>o', desc = 'Open Oil file explorer' },
  { '<leader>fe', desc = 'Open Oil file explorer' },
  { '<leader>fk', desc = 'Keymaps' },
  { '<leader>fh', desc = 'Help tags' },
  { '<leader>fc', desc = 'Commands' },
  { '<leader>fg', desc = 'Git files' },
  { '<leader>fp', desc = 'Jump to bookmark' },
  { '<leader>ba', desc = 'Bookmark current dir' },
  { '<leader>bd', desc = 'Remove bookmark' },
  { '<leader>sd', desc = 'Search diagnostics' },
  { '<leader>z', desc = 'Zen mode' },
  { '<leader>?', '<cmd>CheatSheet<cr>', desc = 'Open cheat sheet' },
  { '<leader>u', '<cmd>UndotreeShow<cr>', desc = 'Undo tree' },
  { '<leader>M', '<cmd>Mason<cr>', desc = 'Mason' },
  { '<leader>cf', desc = 'Format buffer' },
  { '<leader>cl', desc = 'Code actions' },
  { '<leader>cs', desc = 'Signature help' },
  { '<leader>cS', desc = 'Workspace symbols' },
  { '<leader>db', desc = 'Debug UI toggle' },
  { '<leader>de', desc = 'Debug evaluate' },
  { '<leader>gp', desc = 'Preview git hunk' },
  { '<leader>gs', desc = 'Stage git hunk' },
  { '<leader>gr', desc = 'Reset git hunk' },
  { '<leader>Or', desc = 'Run task' },
  { '<leader>Ot', desc = 'Toggle task list' },
  { '<leader>Oo', desc = 'Open task list' },
  { '<leader>Oq', desc = 'Task quick action' },
  { '<leader>Sr', desc = 'Restore session' },
  { '<leader>Sl', desc = 'Restore last session' },
  { '<leader>Ss', desc = 'Save session' },
  { '<leader>Sd', desc = 'Stop session save' },
  { '<leader>Tn', desc = 'Run nearest test' },
  { '<leader>Tf', desc = 'Run test file' },
  { '<leader>Ta', desc = 'Run test suite' },
  { '<leader>Td', desc = 'Debug nearest test' },
  { '<leader>Ts', desc = 'Toggle test summary' },
  { '<leader>To', desc = 'Open test output' },
  { '<leader>TP', desc = 'Toggle test output panel' },
  { '<leader>Tx', desc = 'Stop test run' },
  { '<leader>rr', desc = 'Incremental rename' },
  { '<leader>re', desc = 'Select refactor' },
  { '<leader>rf', desc = 'Extract function' },
  { '<leader>rv', desc = 'Extract variable' },
  { '<leader>ri', desc = 'Inline variable' },
  { '<leader>xx', desc = 'Diagnostics list' },
  { '<leader>xl', desc = 'Diagnostics loclist' },
  { '<leader>xq', desc = 'Quickfix list' },
  { '<leader>xs', desc = 'Document symbols' },
  { '<leader>xt', desc = 'TODO comments' },
  { ']t', desc = 'Next TODO comment' },
  { '[t', desc = 'Previous TODO comment' },
  { ']h', desc = 'Next git hunk' },
  { '[h', desc = 'Previous git hunk' },
  { 's', desc = 'Flash jump' },
  { 'S', desc = 'Flash treesitter' },
  { '<leader>ru', '<cmd>CodeDiff<cr>', desc = 'Code diff not staged' },
  { '<leader>rm', '<cmd>CodeDiff main<cr>', desc = 'Code diff main' },
  { '<leader>rh', '<cmd>CodeDiff HEAD~1<cr>', desc = 'Code diff previous' },
})
